# Generated by Django 5.2.15 on 2026-07-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tbl_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('create_at', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_course',
            name='session_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
