# Generated by Django 5.2.15 on 2026-07-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tbl_student_alter_tbl_course_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_course',
            name='session_name',
            field=models.CharField(max_length=20),
        ),
    ]
