# Generated by Django 5.2.15 on 2026-07-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_session_session_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbll_student',
            fields=[
                ('sid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('emailaddress', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=16)),
                ('contact_no', models.IntegerField()),
                ('gender', models.CharField(max_length=2)),
                ('dob', models.CharField(max_length=15)),
                ('f_name', models.CharField(max_length=225, null=True)),
                ('m_name', models.CharField(max_length=225, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('aadhar_no', models.IntegerField(max_length=15)),
                ('aadhar_pic', models.FileField(null=True, upload_to='student_documents')),
                ('session', models.CharField(max_length=50, null=True)),
                ('course', models.CharField(max_length=500, null=True)),
                ('course_duration', models.CharField(max_length=50, null=True)),
                ('hs_percentage', models.CharField(max_length=20)),
                ('hs_marksheet', models.FileField(null=True, upload_to='student_documents')),
                ('inter_percentage', models.CharField(max_length=20, null=True)),
                ('inter_marksheet', models.FileField(null=True, upload_to='student_documents')),
                ('profile_pic', models.FileField(null=True, upload_to='student_documents')),
                ('sign', models.FileField(null=True, upload_to='student_documents')),
                ('application_status', models.CharField(max_length=20, null=True)),
                ('fees', models.IntegerField(null=True)),
                ('fees_status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
