# Generated by Django 5.2.15 on 2026-07-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tbll_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbll_student',
            name='aadhar_no',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
