# Generated by Django 5.2.15 on 2026-07-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tbll_student_aadhar_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_student',
        ),
    ]
