# Generated by Django 5.2.15 on 2026-07-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_tbl_payment_tbll_student_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbll_student',
            name='application_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
